-- Configurar REPLICA IDENTITY FULL para Realtime capturar dados completos
ALTER TABLE contact_submissions REPLICA IDENTITY FULL;
ALTER TABLE lead_interacoes REPLICA IDENTITY FULL;
ALTER TABLE lead_notas REPLICA IDENTITY FULL;
ALTER TABLE processos REPLICA IDENTITY FULL;
ALTER TABLE processos_andamentos REPLICA IDENTITY FULL;
ALTER TABLE processos_prazos REPLICA IDENTITY FULL;
ALTER TABLE acordos_financeiros REPLICA IDENTITY FULL;
ALTER TABLE parcelas_financeiras REPLICA IDENTITY FULL;
ALTER TABLE despesas REPLICA IDENTITY FULL;
ALTER TABLE profiles REPLICA IDENTITY FULL;